version: '3.9'

services:
  prod:
    container_name: ${CONTAINER_NAME}-container
    image: ${DOCKER_REPO_USER}/${IMAGE_NAME}:${IMAGE_VERSION}
    platform: linux/amd64
    build:
      context: .
      target: Prod
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:3000
    environment:
      - HOST_MONGO=${HOST_MONGO}
      - DB_MONGO_NAME=${DB_MONGO_NAME}
    networks:
      - mynet

networks:
  mynet:
    name: $NETWORK_NAME
