// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injecter

import (
	"crud/interfaces/api"
	"github.com/google/wire"
)

// Injectors from provider.go:

func InitializeAdapter() *api.OrderHandler {
	database := SetupMongoDB()
	iOrderRepository := ProvideOrderRepository(database)
	iOrderService := ProvideOrderService(iOrderRepository)
	orderHandler := ProvideOrderController(iOrderService)
	return orderHandler
}

// provider.go:

var ProviderSet = wire.NewSet(
	RepositoryProviderSet,
	ServiceProviderSet,
	ControllerProviderSet,
)
